feat: create `getErc725yContract` helper
lukso-network/lsp-utils pull request #22
Opened 2023-11-08 11:49 UTC by b00ste

# What does this PR introduce?

This PR creates a new helper that is re-used in LSP4 & LSP12 utils

2023-11-08 13:05 UTC, Hugoo requested changes
nice! Getting cleaner! Good to share the same code under the same function! will make everything easier to read / understand

I would only suggest you an early return so it looks cleaner

2023-11-08 13:05 UTC, Hugoo commented on src/helpers/getErc725yContract/getErc725yContract.ts
> +): Promise<ERC725Y>;
I think these 2 can be merged into one

```suggestion
export async function getErc725yContract(
    erc725y: ERC725Y | BytesLike | string,
    signer: Signer | Wallet | Provider,
): Promise<ERC725Y>;
```

2023-11-08 13:05 UTC, Hugoo commented on src/helpers/getErc725yContract/getErc725yContract.ts
> +    }
Prefer return early pattern: https://medium.com/swlh/return-early-pattern-3d18a41bba8

 ```suggestion    
   if (!isAddress(erc725y) && !isAddressable(erc725y)) {
       throw new Error(
            `The parameter \`erc725y\` is not a valid address nor a valid contract instance of \`ERC725Y\`. Value: '${erc725y}'`,
        );
    } 

    let erc725yContract: ERC725Y;

    if (isAddress(erc725y)) {
        erc725yContract = ERC725Y__factory.connect(erc725y, signer);
    } else if (signer) {
         erc725yContract = erc725y.connect(signer);
    } else {
          erc725yContract = erc725y;
      }
    }
```

(I wrote it on GitHub textarea so might have wrong tab or pb but thats the idea

2023-11-09 11:33 UTC, CJ42 approved these changes

2023-11-09 16:12 UTC, Hugoo approved these changes

2023-11-09 16:16 UTC, merged