refactor: include `fetch` to a `try/catch` block
lukso-network/lsp-utils pull request #25
Opened 2024-01-03 09:41 UTC by b00ste

# What does this PR introduce? 

This PR adds a `try/catch` block for the `fetch` in order to throw with a relevant message.

2024-01-04 11:47 UTC, Hugoo requested changes

2024-01-04 11:47 UTC, Hugoo commented on src/LSP3/getProfileMetadata/getProfileMetadata.ts
> +        profileData = await fetch(profileDataURL).then((response) => response.json());
Don't combine await and then

User either only await or only then.

```suggestion
        const response = await fetch(profileDataURL);
        profileData = await response.json();
```

https://stackoverflow.com/a/69347918

2024-01-04 11:52 UTC, b00ste commented on src/LSP3/getProfileMetadata/getProfileMetadata.ts
> +        profileData = await fetch(profileDataURL).then((response) => response.json());
I see, makes sense, thanks for tip 👍

2024-01-05 12:00 UTC, Hugoo approved these changes

2024-01-05 12:08 UTC, merged